This repository has been moved to: https://github.com/forge/addon-arquillian
============================================================================

Setting up an Arquillian profile
==============
Arquillian supports testing in multiple containers. This is done by using a Maven profile for each container. This makes it possible to have multiple containers configured side-by-side too.
To add a new profile you use the arquillian setup command:

	arquillian-setup
	
This command will prompt which container to use. If  you need to install an additional container profile, run the 

	arquillian-add-container 
	
For managed containers it might make sense to automatically download & install the container during the build to make installation on a build server more easy. This is only supported for AS7 at this moment.
You can also type --<TAB> to auto-complete with the desired options 

Generating tests
================
Writing Arquillian tests is trivial, and is documented well: https://docs.jboss.org/author/display/ARQ/Reference+Guide

Forge can help you get started however. 
	
	arquillian-create-test --targets demo.CoolBean
	
Of course you can use the TAB key to navigate to the class that you want to test.
